version: 2.0

jobs:
  "Test":
    docker:
      - image: fastlanetools/ci:0.4.0
    working_directory: ~/code
    steps:
      - checkout
      - run: sudo pip3 install pipenv
      - run: pipenv install
      - run: gem install bundler -v $(ruby .ci/bundler_version.rb)
      - run: bundle -v
      - run: |
        mv Gemfile.lock Gemfile.lock.old
        bundle install
        git diff Gemfile.lock
        rm Gemfile.lock
        mv Gemfile.lock.old Gemfile.lock
      - run: bundle update
      - run: pipenv run bundle exec fastlane test
      - run: bundle exec rubocop
      - run: bundle exec danger || echo "danger failed, moving on"
  "Deploy":
    docker:
      - image: fastlanetools/ci:0.4.0
    working_directory: ~/code
    steps:
      - checkout
      - run: sudo pip3 install pipenv
      - run: pipenv install
      - run: gem install bundler -v $(ruby .ci/bundler_version.rb)
      - run: bundle update
      - run: pipenv run ./scripts/ci/deploy.sh

workflows:
  version: 2
  build:
    jobs:
      - "Test"
      - "Deploy":
          filters:
            branches:
              only: master
